server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        # Esto maneja mejor los slashes
        rewrite ^/api/(.*)$ /$1 break;
        
        include fastcgi_params;
        fastcgi_pass proximarkt-backend:9000;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_param SCRIPT_FILENAME /var/www/html/public/index.php;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        
        # Necesario para Laravel y HTTPS
        fastcgi_param HTTP_X_FORWARDED_PROTO https;
    }
}