server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # CONFIGURACIÓN PARA LARAVEL (PHP-FPM)
    location /api {
        # Esto elimina el prefijo /api para que Laravel reciba la ruta limpia
        rewrite ^/api/(.*)$ /$1 break;

        # IMPORTANTE: Cambiamos proxy_pass por fastcgi_pass
        fastcgi_pass proximarkt-backend:9000;
        include fastcgi_params;
        
        # Le decimos a PHP exactamente qué archivo ejecutar
        fastcgi_param SCRIPT_FILENAME /var/www/html/public/index.php;
        fastcgi_param DOCUMENT_ROOT /var/www/html/public;

        # Headers de seguridad y protocolo
        fastcgi_param HTTP_X_FORWARDED_FOR $proxy_add_x_forwarded_for;
        fastcgi_param HTTP_X_FORWARDED_PROTO https;
    }
}