site_name: Proxi Markt
site_description: Documentación de la base de datos y sistema de Proxi Markt

# Extensiones de Markdown
markdown_extensions:
  - admonition 
  - attr_list 
  - pymdownx.details 
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite 
  - pymdownx.snippets 
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

# Configuración de navegación
nav:
  - Inicio: index.md
  - Iniciar proyecto: documentacion_iniciar_proyecto.md
  - Despliegue producción: despliegue_produccion.md
  - Base de datos: documentacio_bd.md
  - Prototipo: documentacion_prototipo.md
  - Documentación código: documentacion_codigo.md

# Plugins adicionales
plugins:
  - search

extra_javascript:
  - https://unpkg.com/mermaid/dist/mermaid.min.js
