version: '3.8'

services:
  # --- FRONTEND (Vue.js) ---
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=https://proximarkt.francecentral.cloudapp.azure.com/api
    container_name: proximarkt-frontend
    restart: always
    networks:
      - proxy_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`proximarkt.francecentral.cloudapp.azure.com`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
      - "traefik.http.routers.frontend.priority=1"

  # --- BACKEND (Laravel) ---
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: proximarkt-backend
    restart: always
    env_file: ../backend/.env 
    volumes:
      - backend_storage:/var/www/html/storage
    networks:
      - proxy_net
      - backend_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`proximarkt.francecentral.cloudapp.azure.com`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=myresolver"
      - "traefik.http.routers.backend.priority=100"
      # Quitamos el prefijo /api para que Laravel reciba la ruta limpia
      - "traefik.http.middlewares.api-strip.stripprefix.prefixes=/api"
      - "traefik.http.routers.backend.middlewares=api-strip"
      - "traefik.http.services.backend.loadbalancer.server.port=80"

  # --- BASE DE DATOS ---
  mysql:
    image: mysql:8.0
    container_name: proximarkt-mysql
    restart: always
    environment:
      MYSQL_DATABASE: proxi_markt 
      MYSQL_ROOT_PASSWORD: alumno  
      MYSQL_USER: alumno           
      MYSQL_PASSWORD: alumno
    volumes:
      - db_data:/var/lib/mysql
      - ../docker/database/base.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend_net

networks:
  proxy_net:
    external: true # Indica que esta red la creó el contenedor de Traefik
  backend_net:
    driver: bridge

volumes:
  db_data:
  backend_storage: