version: '3.8'

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: always
    command:
      - "--log.level=DEBUG"
      # Puntos de entrada
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      
      # Redirección automática de HTTP a HTTPS
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"

      # Configuración de Docker
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=proxy_net"
      
      # Let's Encrypt (Certificados Automáticos)
      - "--certificatesresolvers.myresolver.acme.email=davcamure@alu.edu.gva.es"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      
      # API y Dashboard
      - "--api.dashboard=true"
      - "--api.insecure=true"
    labels:
      - "traefik.enable=true"
      # Definimos el router para el dashboard
      - "traefik.http.routers.api.rule=Host(`proximarkt.francecentral.cloudapp.azure.com`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.entrypoints=websecure"
      # ACTIVAMOS EL RESOLVER AQUÍ:
      - "traefik.http.routers.api.tls.certresolver=myresolver"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt" # Donde se guardarán tus certificados
    networks:
      - proxy_net

networks:
  proxy_net:
    driver: bridge
    name: proxy_net