version: '3.8'

services:
 # --- DOCKER PROXY (El Traductor Oficial) ---
  docker-proxy:
    image: tecnativa/docker-socket-proxy
    container_name: docker-proxy
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CONTAINERS=1
      - NETWORKS=1
      - SERVICES=1  # Añadido para Traefik v3
    networks:
      - internal-net

  # --- TRAEFIK ---
  traefik:
    image: traefik:v3.3
    container_name: traefik
    restart: unless-stopped
    depends_on:
      - docker-proxy
    environment:
      - DOCKER_API_VERSION=1.44
    command:
      - "--providers.docker=true"
      - "--providers.docker.endpoint=tcp://docker-proxy:2375"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.allowEmptyServices=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=tu-correo@alu.edu.gva.es"
      - "--certificatesresolvers.myresolver.acme.storage=/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./acme.json:/acme.json"
    networks:
      - proxy-net
      - internal-net

  # --- MYSQL ---
  mysql:
    image: mysql:8.0
    container_name: proximarkt_db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - ../docker/database/.env.database
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - internal-net

  # --- PHP ---
  php:
    build:
      context: ..
      dockerfile: despliegue/Dockerfile.prod
    container_name: proximarkt_php
    restart: unless-stopped
    env_file: ../docker/.env.app
    volumes:
      # IMPORTANTE: Mantenemos esto, pero hay que borrar el volumen antiguo
      - php_assets:/var/www/html
      - ./storage_data:/var/www/html/storage/app/public
    networks:
      - internal-net

  # --- NGINX ---
  nginx:
    image: nginx:stable-alpine
    container_name: proximarkt_nginx
    restart: unless-stopped
    volumes:
      - ./prod.conf:/etc/nginx/conf.d/default.conf
      - php_assets:/var/www/html:ro
    depends_on:
      - php
    networks:
      - internal-net
      - proxy-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.proximarkt.rule=Host(`proximarkt.francecentral.cloudapp.azure.com`)"
      - "traefik.http.routers.proximarkt.entrypoints=websecure"
      - "traefik.http.routers.proximarkt.tls.certresolver=myresolver"
      - "traefik.http.services.proximarkt-svc.loadbalancer.server.port=80"

volumes:
  mysql_data:
  php_assets:
  acme_data:

networks:
  proxy-net:
  internal-net: