services:
  # --- TRAEFIK (Gestión de SSL y Proxy Externo) ---
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    environment:
      - DOCKER_API_VERSION=1.44
    command:
      - "--providers.docker=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=tu-correo@alu.edu.gva.es"
      - "--certificatesresolvers.myresolver.acme.storage=/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./acme.json:/acme.json"
    networks:
      - proxy-net

  # --- MYSQL (Base de datos) ---
  mysql:
    image: mysql:8.0
    container_name: proximarkt_db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - ../docker/database/.env.database
    volumes:
      - mysql_data:/var/lib/mysql
      - ../docker/database/base.sql:/docker-entrypoint-initdb.d/01-base.sql:ro
    networks:
      - internal-net

  # --- PHP (Procesamiento de Laravel) ---
  php:
    build:
      context: ..
      dockerfile: despliegue/Dockerfile.prod
    container_name: proximarkt_php
    restart: unless-stopped
    env_file: ../docker/.env.app
    volumes:
      # Mapeamos la raíz para que PHP vea la carpeta /backend
      - ..:/var/www/html
    networks:
      - internal-net

  # --- NGINX (Servidor Web para Vue y Laravel) ---
  nginx:
    image: nginx:stable-alpine
    container_name: proximarkt_nginx
    restart: unless-stopped
    volumes:
      - ./prod.conf:/etc/nginx/conf.d/default.conf
      # Nginx necesita ver TODO para servir el frontend/dist y el backend/public
      - ..:/var/www/html:ro
    depends_on:
      - php
    networks:
      - internal-net
      - proxy-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.proximarkt.rule=Host(`proximarkt.francecentral.cloudapp.azure.com`)"
      - "traefik.http.routers.proximarkt.entrypoints=websecure"
      - "traefik.http.routers.proximarkt.tls.certresolver=myresolver"
      - "traefik.http.services.proximarkt-svc.loadbalancer.server.port=80"

volumes:
  mysql_data:

networks:
  proxy-net:
  internal-net:
