server {
    listen 80;
    server_name proximarkt.francecentral.cloudapp.azure.com;
    index index.html index.php;

    # --- FRONTEND (VUE) ---
    root /var/www/html/frontend/dist;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # --- BACKEND (LARAVEL API) ---
    location /api {
        # Usamos alias para apuntar a la carpeta public de Laravel
        alias /var/www/html/backend/public;
        
        # Intentamos servir el archivo directamente, si no, saltamos a @laravel
        try_files $uri $uri/ @laravel;

        # Procesamiento de PHP dentro de /api
        location ~ \.php$ {
            fastcgi_pass php:9000;
            include fastcgi_params;
            # Forzamos la ruta al index.php del backend
            fastcgi_param SCRIPT_FILENAME /var/www/html/backend/public/index.php;
            # Importante para que Laravel no se pierda con las rutas
            fastcgi_param SCRIPT_NAME /index.php;
        }
    }

    # El bloque que gestiona las rutas de Laravel
    location @laravel {
        # Capturamos lo que viene después de /api/ y se lo pasamos al index.php
        rewrite ^/api/(.*)$ /api/index.php?/$1 last;
    }

}