server {
    listen 80;
    index index.html index.php;
    
    # RUTA AL FRONTEND (VUE)
    # Importante: Asegúrate de que has hecho el 'npm run build' en Vue
    root /var/www/html/frontend/dist; 

    location / {
        try_files $uri $uri/ /index.html;
    }

    # RUTA AL BACKEND (LARAVEL API)
    location /api {
        alias /var/www/html/backend/public;
        try_files $uri $uri/ @laravel;

        location ~ \.php$ {
            fastcgi_pass php:9000;
            # Importante: Ruta absoluta al index.php de Laravel
            fastcgi_param SCRIPT_FILENAME /var/www/html/backend/public/index.php;
            include fastcgi_params;
        }
    }

    location @laravel {
        rewrite /api/(.*)$ /api/index.php?/$1 last;
    }
}